[workspace]
resolver = "2"
members = [
	"client",
	"common",
	"server",
]

[workspace.package]
version = "0.0.0"
edition = "2021"
readme = "readme.md"
license = "MPL-2.0"

[workspace.dependencies]
"crowdquiz-common".path = "common"